### ISSUE TITLE
Validation script and default branches

### ISSUE THREAD

**Issue by leogdion** [SwiftPackageIndex/PackageListValidator#2]
as noted by @daveverwer:

> /cc @leogdion
> 
> I wonder if there's an easy way to make the validation script work with default branches as there was another pull request today that came in with two packages that do not use `master`.
> 
> The [GitHub API to get repository details](https://developer.github.com/v3/repos/#get-a-repository) does return a `default_branch` property which is probably the quickest and easiest way to figure out the correct raw URL to the Package.swift.
> 
> No rush for this, but I wanted to log it

referenced in [daveverwer/SwiftPMLibrary #271](https://github.com/daveverwer/SwiftPMLibrary/issues/271)

**Comment by daveverwer** [comment]
Closing in favour of #15
